// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTeXBkbJEmHDU6JFtZ9IYrXXvJG48eZqY',
    appId: '1:796722015583:web:e3b6e63cff1e57c45c1aea',
    messagingSenderId: '796722015583',
    projectId: 'join-your-group',
    authDomain: 'join-your-group.firebaseapp.com',
    storageBucket: 'join-your-group.appspot.com',
    measurementId: 'G-VX6DZMF2P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaY5ayTOj1plAJsz96dGm_gtUNpfrWkOo',
    appId: '1:796722015583:android:4a7d5695da4277165c1aea',
    messagingSenderId: '796722015583',
    projectId: 'join-your-group',
    storageBucket: 'join-your-group.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwZLcJWnlMSoK-n-0oGx_9rzawi0ApR8M',
    appId: '1:796722015583:ios:4e864d6b20f9fc045c1aea',
    messagingSenderId: '796722015583',
    projectId: 'join-your-group',
    storageBucket: 'join-your-group.appspot.com',
    iosBundleId: 'com.example.joinYourGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwZLcJWnlMSoK-n-0oGx_9rzawi0ApR8M',
    appId: '1:796722015583:ios:4e864d6b20f9fc045c1aea',
    messagingSenderId: '796722015583',
    projectId: 'join-your-group',
    storageBucket: 'join-your-group.appspot.com',
    iosBundleId: 'com.example.joinYourGroup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTeXBkbJEmHDU6JFtZ9IYrXXvJG48eZqY',
    appId: '1:796722015583:web:621ba0bb3e3092995c1aea',
    messagingSenderId: '796722015583',
    projectId: 'join-your-group',
    authDomain: 'join-your-group.firebaseapp.com',
    storageBucket: 'join-your-group.appspot.com',
    measurementId: 'G-DM7G3299MC',
  );
}
